apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service-deployment
  labels:
    app: book-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
      - name: book-service
        image: book-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001   # HTTP
        - containerPort: 3011   # gRPC
        env:
        - name: BOOK_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: my-app-config
              key: BOOK_SERVICE_PORT
        - name: BOOK_GRPC_PORT
          valueFrom:
            configMapKeyRef:
              name: my-app-config
              key: BOOK_GRPC_PORT
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: my-app-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: my-app-config
              key: POSTGRES_PORT
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: my-app-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: my-app-config
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: my-app-config
              key: POSTGRES_DB
        - name: POSTGRES_SCHEMA
          valueFrom:
            configMapKeyRef:
              name: my-app-config
              key: POSTGRES_SCHEMA      
