apiVersion: v1
kind: Service
metadata:
  name: rental-service
spec:
  selector:
    app: rental-service
  ports:
  - name: http
    protocol: TCP
    port: 3002
    targetPort: 3002
  - name: grpc
    protocol: TCP
    port: 3022
    targetPort: 3022
